backend:
  name: github
  repo: barberloungerio/barberloungerio.com.br
  branch: main
  base_url: https://auth.decapcms.org
  site_id: barberloungerio.com.br

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {name: "title", label: "Título", widget: "string"}
      - {name: "body", label: "Corpo", widget: "markdown"}
